#pragma once

#include <iostream>
#include <set>
#include <sc2api/sc2_typeenums.h>
#include <sc2api/sc2_unit.h>


namespace Aeolus {
	namespace constants
	{
		enum class ManagerName
		{
			UNIT_ROLE_MANAGER,
			RESOURCE_MANAGER,
			PATH_MANAGER,
			NEUTRAL_UNIT_MANAGER
		};

		enum class ManagerRequestType
		{
			GET_UNITS_FROM_ROLE,
			CATCH_UNIT,
			GET_ALL_MINERAL_PATCHES,
			ASSIGN_WORKER_TO_PATCH,
			CLEAR_ASSIGNMENT,
			CALCULATE_MINERAL_GATHERING_POINTS,
			GET_MINERAL_GATHERING_POINTS,
			GET_WORKERS_TO_PATCH,
			ASSIGN_INITIAL_WORKERS,
			GET_ALL_VESPENE_GEYSERS,
			GET_ALL_DESTRUCTABLES,
		};

		enum class UnitRole
		{
			GATHERING
		};
		std::string ManagerNameToString(ManagerName name);
		std::string ManagerRequestTypeToString(ManagerRequestType requestType);
	
		const double MINING_RADIUS{ 1.35 };
		const double TOWNHALL_DISTANCE_FACTOR{ 1.08 };
		const double MINING_BOOST_MIN_RADIUS{ 0.5625 };
		const double MINING_BOOST_MAX_RADIUS{ 4.0 };
		const double TOWNHALL_RADIUS{ 2.75 };

		const float CAMERA_WIDTH{ 24.0f };
		const int FEATURE_LAYER_SIZE{ 3 };
		const int PIXEL_DRAW_SIZE{ 180 };
		constexpr int DRAW_SIZE = FEATURE_LAYER_SIZE * PIXEL_DRAW_SIZE;

		const std::set<::sc2::UnitTypeID> MINERAL_IDS =
		{
			::sc2::UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_MINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_MINERALFIELD450,
			::sc2::UNIT_TYPEID::NEUTRAL_MINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_LABMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_LABMINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD750,
			::sc2::UNIT_TYPEID::MINERALFIELDOPAQUE,
			::sc2::UNIT_TYPEID::MINERALFIELDOPAQUE900
		};

		const std::set<::sc2::UnitTypeID> VESPENE_IDS =
		{
			::sc2::UNIT_TYPEID::NEUTRAL_VESPENEGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_SPACEPLATFORMGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_RICHVESPENEGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_PROTOSSVESPENEGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERVESPENEGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_SHAKURASVESPENEGEYSER
		};

		const std::set<::sc2::UnitTypeID> WATCHTOWER_IDS =
		{
			::sc2::UNIT_TYPEID::NEUTRAL_XELNAGATOWER
		};
	}
}