#pragma once

#include <iostream>
#include <set>
#include <sc2api/sc2_typeenums.h>
#include <sc2api/sc2_unit.h>


namespace Aeolus {
	namespace constants
	{
		enum class ManagerName
		{
			UNIT_ROLE_MANAGER,
			RESOURCE_MANAGER,
			PATH_MANAGER,
			NEUTRAL_UNIT_MANAGER,
			UNIT_FILTER_MANAGER,
			UNIT_PROPERTY_MANAGER
		};

		enum class ManagerRequestType
		{
			GET_UNITS_FROM_ROLE,
			CATCH_UNIT,
			GET_ALL_MINERAL_PATCHES,
			ASSIGN_WORKER_TO_PATCH,
			CLEAR_ASSIGNMENT,
			CALCULATE_MINERAL_GATHERING_POINTS,
			GET_MINERAL_GATHERING_POINTS,
			GET_WORKERS_TO_PATCH,
			ASSIGN_INITIAL_WORKERS,
			GET_ALL_VESPENE_GEYSERS,
			GET_ALL_DESTRUCTABLES,
			GET_ALL_STRUCTURES,
			GET_DEFAULT_GRID_DATA,

			// UnitFilterManager
			GET_OWN_WORKERS,

			// UnitPropertyManager
			CAN_ATTACK_GROUND,
			CAN_ATTACK_AIR,
			GROUND_RANGE,
			AIR_RANGE
		};

		enum class UnitRole
		{
			GATHERING
		};
		std::string ManagerNameToString(ManagerName name);
		std::string ManagerRequestTypeToString(ManagerRequestType requestType);
	
		const double MINING_RADIUS{ 1.35 };
		const double TOWNHALL_DISTANCE_FACTOR{ 1.08 };
		const double MINING_BOOST_MIN_RADIUS{ 0.5625 };
		const double MINING_BOOST_MAX_RADIUS{ 4.0 };
		const double TOWNHALL_RADIUS{ 2.75 };

		const float CAMERA_WIDTH{ 24.0f };
		const int FEATURE_LAYER_SIZE{ 120 };
		const int PIXEL_DRAW_SIZE{ 4 };
		constexpr int DRAW_SIZE = FEATURE_LAYER_SIZE * PIXEL_DRAW_SIZE;

		const std::set<::sc2::UnitTypeID> MINERAL_IDS =
		{
			::sc2::UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_MINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_MINERALFIELD450,
			::sc2::UNIT_TYPEID::NEUTRAL_MINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_LABMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_LABMINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD750,
			::sc2::UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD,
			::sc2::UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD750,
			::sc2::UNIT_TYPEID::MINERALFIELDOPAQUE,
			::sc2::UNIT_TYPEID::MINERALFIELDOPAQUE900
		};

		const std::set<::sc2::UnitTypeID> VESPENE_IDS =
		{
			::sc2::UNIT_TYPEID::NEUTRAL_VESPENEGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_SPACEPLATFORMGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_RICHVESPENEGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_PROTOSSVESPENEGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_PURIFIERVESPENEGEYSER,
			::sc2::UNIT_TYPEID::NEUTRAL_SHAKURASVESPENEGEYSER
		};

		const std::set<::sc2::UnitTypeID> WATCHTOWER_IDS =
		{
			::sc2::UNIT_TYPEID::NEUTRAL_XELNAGATOWER
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE2X2_IDS =
		{
			::sc2::UNIT_TYPEID::ROCKS2X2NONCONJOINED,
			::sc2::UNIT_TYPEID::DEBRIS2X2NONCONJOINED
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE4X4_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLECITYDEBRIS4X4,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEDEBRIS4X4,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICE4X4,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCK4X4,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX14X4
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE4X2_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLECITYDEBRIS2X4HORIZONTAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICE2X4HORIZONTAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCK2X4HORIZONTAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX12X4HORIZONTAL
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE2X4_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLECITYDEBRIS2X4VERTICAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICE2X4VERTICAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCK2X4VERTICAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX12X4VERTICAL
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE6X2_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLECITYDEBRIS2X6HORIZONTAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICE2X6HORIZONTAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCK2X6HORIZONTAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX12X6HORIZONTAL
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE2X6_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLECITYDEBRIS2X6VERTICAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICE2X6VERTICAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCK2X6VERTICAL,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX12X6VERTICAL
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE4X12_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX1VERTICALHUGE,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICEVERTICALHUGE
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE12X4_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX1HORIZONTALHUGE,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICEHORIZONTALHUGE
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLE6X6_IDS =
		{
			::sc2::UNIT_TYPEID::NEUTRAL_DESTRUCTIBLECITYDEBRIS6X6,
			::sc2::UNIT_TYPEID::NEUTRAL_DESTRUCTIBLEDEBRIS6X6,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICE6X6,
			::sc2::UNIT_TYPEID::NEUTRAL_DESTRUCTIBLEROCK6X6,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX16X6
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLEBLUR_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLECITYDEBRISHUGEDIAGONALBLUR,
			::sc2::UNIT_TYPEID::NEUTRAL_DESTRUCTIBLEDEBRISRAMPDIAGONALHUGEBLUR,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICEDIAGONALHUGEBLUR,
			::sc2::UNIT_TYPEID::NEUTRAL_DESTRUCTIBLEROCKEX1DIAGONALHUGEBLUR,
			::sc2::UNIT_TYPEID::DESTRUCTIBLERAMPDIAGONALHUGEBLUR
		};

		const std::set<::sc2::UnitTypeID> DESTRUCTABLEULBR_IDS =
		{
			::sc2::UNIT_TYPEID::DESTRUCTIBLECITYDEBRISHUGEDIAGONALULBR,
			::sc2::UNIT_TYPEID::NEUTRAL_DESTRUCTIBLEDEBRISRAMPDIAGONALHUGEULBR,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEICEDIAGONALHUGEULBR,
			::sc2::UNIT_TYPEID::DESTRUCTIBLEROCKEX1DIAGONALHUGEULBR,
			::sc2::UNIT_TYPEID::DESTRUCTIBLERAMPDIAGONALHUGEULBR
		};

		const std::set<::sc2::UnitTypeID> BUILDINGS_2X2 =
		{
			::sc2::UNIT_TYPEID::TERRAN_SUPPLYDEPOT,
			::sc2::UNIT_TYPEID::PROTOSS_PYLON,
			::sc2::UNIT_TYPEID::PROTOSS_DARKSHRINE,
			::sc2::UNIT_TYPEID::PROTOSS_PHOTONCANNON,
			::sc2::UNIT_TYPEID::TERRAN_TECHLAB,
			::sc2::UNIT_TYPEID::TERRAN_STARPORTTECHLAB,
			::sc2::UNIT_TYPEID::TERRAN_FACTORYTECHLAB,
			::sc2::UNIT_TYPEID::TERRAN_BARRACKSTECHLAB,
			::sc2::UNIT_TYPEID::TERRAN_REACTOR,
			::sc2::UNIT_TYPEID::TERRAN_STARPORTREACTOR,
			::sc2::UNIT_TYPEID::TERRAN_FACTORYREACTOR,
			::sc2::UNIT_TYPEID::TERRAN_BARRACKSREACTOR,
			::sc2::UNIT_TYPEID::TERRAN_MISSILETURRET,
			::sc2::UNIT_TYPEID::ZERG_SPORECRAWLER,
			::sc2::UNIT_TYPEID::ZERG_SPINECRAWLER,
			::sc2::UNIT_TYPEID::ZERG_SPIRE,
			::sc2::UNIT_TYPEID::ZERG_GREATERSPIRE
		};

		const std::set<::sc2::UnitTypeID> BUILDINGS_3X3 =
		{
			::sc2::UNIT_TYPEID::PROTOSS_GATEWAY,
			::sc2::UNIT_TYPEID::PROTOSS_WARPGATE,
			::sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE,
			::sc2::UNIT_TYPEID::PROTOSS_FORGE,
			::sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY,
			::sc2::UNIT_TYPEID::PROTOSS_ROBOTICSBAY,
			::sc2::UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE,
			::sc2::UNIT_TYPEID::PROTOSS_TWILIGHTCOUNCIL,
			::sc2::UNIT_TYPEID::PROTOSS_STARGATE,
			::sc2::UNIT_TYPEID::PROTOSS_FLEETBEACON,
			::sc2::UNIT_TYPEID::PROTOSS_ASSIMILATOR,
			::sc2::UNIT_TYPEID::PROTOSS_ASSIMILATORRICH,
			::sc2::UNIT_TYPEID::ZERG_SPAWNINGPOOL,
			::sc2::UNIT_TYPEID::ZERG_ROACHWARREN,
			::sc2::UNIT_TYPEID::ZERG_HYDRALISKDEN,
			::sc2::UNIT_TYPEID::ZERG_BANELINGNEST,
			::sc2::UNIT_TYPEID::ZERG_EVOLUTIONCHAMBER,
			::sc2::UNIT_TYPEID::ZERG_NYDUSNETWORK,
			::sc2::UNIT_TYPEID::ZERG_NYDUSCANAL,
			::sc2::UNIT_TYPEID::ZERG_EXTRACTOR,
			::sc2::UNIT_TYPEID::ZERG_EXTRACTORRICH,
			::sc2::UNIT_TYPEID::ZERG_INFESTATIONPIT,
			::sc2::UNIT_TYPEID::ZERG_ULTRALISKCAVERN,
			::sc2::UNIT_TYPEID::TERRAN_BARRACKS,
			::sc2::UNIT_TYPEID::TERRAN_FACTORY,
			::sc2::UNIT_TYPEID::TERRAN_STARPORT,
			::sc2::UNIT_TYPEID::TERRAN_ENGINEERINGBAY,
			::sc2::UNIT_TYPEID::TERRAN_GHOSTACADEMY,
			::sc2::UNIT_TYPEID::TERRAN_FUSIONCORE,
			::sc2::UNIT_TYPEID::TERRAN_BUNKER,
			::sc2::UNIT_TYPEID::TERRAN_ARMORY,
			::sc2::UNIT_TYPEID::TERRAN_REFINERY,
			::sc2::UNIT_TYPEID::TERRAN_REFINERYRICH
		};

		const std::set<::sc2::UnitTypeID> BUILDING_5X5
		{
			::sc2::UNIT_TYPEID::PROTOSS_NEXUS,
			::sc2::UNIT_TYPEID::ZERG_HATCHERY,
			::sc2::UNIT_TYPEID::ZERG_HIVE,
			::sc2::UNIT_TYPEID::ZERG_LAIR,
			::sc2::UNIT_TYPEID::TERRAN_COMMANDCENTER,
			::sc2::UNIT_TYPEID::TERRAN_ORBITALCOMMAND,
			::sc2::UNIT_TYPEID::TERRAN_PLANETARYFORTRESS
		};

		const std::set<::sc2::UnitTypeID> WORKER_TYPES
		{
			::sc2::UNIT_TYPEID::TERRAN_SCV,
			::sc2::UNIT_TYPEID::PROTOSS_PROBE,
			::sc2::UNIT_TYPEID::ZERG_DRONE
		};

		const std::set<::sc2::UnitTypeID> BUILDINGS = []
		{
			std::set<::sc2::UnitTypeID> BUILDINGS_;
			// Insert all elements from BUILDINGS_2X2
			BUILDINGS_.insert(BUILDINGS_2X2.begin(), BUILDINGS_2X2.end());
			// Insert all elements from BUILDINGS_3X3
			BUILDINGS_.insert(BUILDINGS_3X3.begin(), BUILDINGS_3X3.end());
			// Insert all elements from BUILDING_5X5
			BUILDINGS_.insert(BUILDING_5X5.begin(), BUILDING_5X5.end());
			return BUILDINGS_;
		}();
	}
}