name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '**.md'

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  ladder_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libprotobuf-dev protobuf-compiler libsdl2-dev

      - name: Configure
        run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_FOR_LADDER=ON -DBUILD_WITH_RENDERER=OFF -DSC2_VERSION="4.10.0"

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }} --parallel 2

      - name: Archive Executable
        run: |
          mkdir -p artifacts
          cp "${{ env.BUILD_DIR }}/bin/Aeolus" artifacts/Aeolus

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Aeolus
          path: artifacts/Aeolus
